name: $(version)_iOS_Export

trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: Chartmuseum  # This is the 'Variable group name' from your screenshot
  - name: version
    value: $[format('1.0.{0}', counter('1.0', 0))]

jobs:
  - job: ExportiOSCredentials
    displayName: "Extract iOS Provisioning and Certificates"
    steps:
      # Step 1: Create the credentials text file
      # Using the exact name 'P12password' from your screenshot
      - script: |
          echo "CmPassword: $(CmPassword)" > info.txt
        displayName: "Generate dockertoken info Text File"

      - task: CopyFiles@2
        inputs:
          Contents: 'info.txt'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: "Stage Credentials Text"

      # Step 5: Publish
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'dockertoken'
          publishLocation: 'Container'