import {useNavigate, useParams} from "react-router-dom";
import Button from "./common/forms/Button";
import FormField from "./common/forms/FormField";
import TextEditor from "./common/forms/TextEditor";
import {useEffect, useState} from "react";
import {apiClient} from "../client";
import {IPartner, UpdatePartner} from "../types/partners";
import {KeyValuePair} from "../types/common";
import KeyValueEditor from "./common/forms/KeyValueEditor";
import Authorize from "src/components/common/authorize/authorize";
import {ISubscription} from "src/types/subscriptions";


const Component = () => {
    const navigate = useNavigate();
    const {id} = useParams();
    const [partner, setPartner] = useState<IPartner>();
    const [updatePartnerData, setUpdatePartnerData] = useState<UpdatePartner>({});
    const [hasUnsavedApiCredentials, setHasUnsavedApiCredentials] = useState(false);
    const nav = useNavigate()
    useEffect(() => {
        if (id) {
            refreshPartner(id);
        }

    }, [id]);
    useEffect(() => {
        setUpdatePartnerData({
            name: partner?.name,
            apiCredentials: partner?.apiCredentials,
            adapterProperties: partner?.adapterProperties
        })
        setHasUnsavedApiCredentials(false);
    }, [partner])

    const refreshPartner = async (id: string) => {
        let res = await apiClient.findPartner(id);
        if (res.succeeded) setPartner(res.data);
    }

    const updatePartner = async () => {
        let res = await apiClient.updatePartner(id!, updatePartnerData);
        if (res.succeeded) {
            setHasUnsavedApiCredentials(false);
            await refreshPartner(id!);
        }
    }
    const deletePartner = async () => {
        let res = await apiClient.deletePartner(id!);
        if (res.succeeded) navigate('/partners')
    }

    const addApiCredential = async (kv: KeyValuePair): Promise<string | null> => {
        let pparr = [...(updatePartnerData.apiCredentials ?? [])];
        let res = await apiClient.generatePartnerKey();
        if (res.succeeded) {
            kv.value = res.data
            pparr.push(kv);
            setHasUnsavedApiCredentials(true);
            setUpdatePartnerData({...updatePartnerData, apiCredentials: pparr})
            return res.data;
        }
        return null;
    }
    const removeApiKey = (kv: KeyValuePair) => {
        let pparr: KeyValuePair[] = [];
        updatePartnerData.apiCredentials?.forEach(pp => {
            if (pp.value != kv.value || pp.key != kv.key) pparr.push(pp);
        });
        setHasUnsavedApiCredentials(true);
        setUpdatePartnerData({...updatePartnerData, apiCredentials: pparr})
    }

    const validateApiCredential = (kv: KeyValuePair) => {
        if (!kv.key?.trim()) return "Enter a name for this credential. It is only a label, not the API key.";
        if (updatePartnerData.apiCredentials?.some(i => i.key.trim().toLowerCase() === kv.key.trim().toLowerCase())) {
            return "A credential with this name already exists.";
        }

        return null;
    }

    return (
        <div className="flex flex-col w-full gap-10 ">
            <div className={"md:w-1/3 bg-white flex flex-col h-fit p-2 rounded-lg shadow-lg"}>


                <div className="  flex flex-col md:flex-row justify-between items-end">
                    <FormField title="Name" className="w-3/4">
                        <TextEditor value={updatePartnerData?.name} onChange={(t) => setUpdatePartnerData({
                            ...updatePartnerData,
                            name: t
                        })}/>
                    </FormField>
                    <div className={" "}>

                        <Button onClick={deletePartner}
                        >
                            Delete
                        </Button>

                    </div>
                </div>
                <div className="mt-5 flex w-full flex-col">

                    <Authorize roles={["Admin", "Member"]}>

                        <KeyValueEditor hideEmptyLabel values={updatePartnerData?.apiCredentials}
                                        title={'Api Credentials'}
                                        keyLabel={"Name"} valueLabel={"Key"}
                                        onAddWithReveal={addApiCredential} onSaveAfterReveal={updatePartner}
                                        onRemove={removeApiKey} addLabel={"Add New Api Credentials"}
                                        valueAutoGeneratedOnAdd={true}
                                        keyPlaceholder={"e.g. OFS production"}
                                        description={"Name is only a label. Use the generated Key as the partnerKey when calling the API."}
                                        validate={validateApiCredential}
                        />
                    </Authorize>
                    {hasUnsavedApiCredentials && (
                        <div className="mt-3 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
                            API credential changes are not saved yet. Click Save at the bottom of the page.
                        </div>
                    )}

                </div>
                <div className=" mt-5  flex  w-full ">

                    <Authorize roles={["Admin", "Member"]}>
                        <KeyValueEditor
                            values={updatePartnerData?.adapterProperties
                                ? Object.entries(updatePartnerData.adapterProperties).map(([key, value]) => ({key, value}))
                                : []}
                            title={'Adapter Properties'}
                            keyLabel={"Name"} valueLabel={"Value"}
                            onAdd={(kv) => setUpdatePartnerData({
                                ...updatePartnerData,
                                adapterProperties: {...(updatePartnerData.adapterProperties ?? {}), [kv.key]: kv.value}
                            })}
                            onRemove={(kv) => {
                                const updated = {...(updatePartnerData.adapterProperties ?? {})};
                                delete updated[kv.key];
                                setUpdatePartnerData({...updatePartnerData, adapterProperties: updated});
                            }}
                            onEdit={(kv) => setUpdatePartnerData({
                                ...updatePartnerData,
                                adapterProperties: {...(updatePartnerData.adapterProperties ?? {}), [kv.key]: kv.value}
                            })}
                            addLabel={"Add Property"}
                        />
                    </Authorize>

                </div>
                <div className={"flex w-full flex-row-reverse gap-2 mt-3"}>

                    <Authorize roles={["Admin", "Member"]}>
                        <Button
                            onClick={updatePartner}
                        >Save
                        </Button>
                    </Authorize>
                    <Button
                        variant={"secondary"}
                        onClick={() => navigate('/partners')}
                    >Cancel
                    </Button>
                </div>
            </div>
            {
                (partner?.subscriptions && partner.subscriptions?.length > 0) &&
                <div className="  md:w-1/3   flex  justify-between">


                    <div className="w-full shadow-lg  bg-white  rounded-xl overflow-hidden  pt-2">
                        <div
                            className="text-2xl w-full py-2 font-bold tracking-wide px-5 text-primary-600">Subscriptions
                        </div>
                        <table className=" min-w-full">
                            <thead className="border-y bg-gray-50">
                            <tr>
                                <th scope="col" className="text-sm font-medium text-gray-900 px-6 py-1 text-left">
                                    ID
                                </th>
                                <th scope="col" className="text-sm font-medium text-gray-900 px-6 py-1 text-left">
                                    Name
                                </th>

                            </tr>
                            </thead>
                            <tbody>
                            {
                                partner?.subscriptions?.map((i: ISubscription) => (
                                    <tr key={i.id} className="bg-white border-b cursor-pointer"
                                        onClick={() => nav(`/subscriptions/${i.id}`)}>
                                        <td className="text-sm text-gray-900 font-light px-6 py-1 whitespace-nowrap">
                                            {i.id}
                                        </td>
                                        <td className="text-sm text-gray-900 font-light px-6 py-1 whitespace-nowrap">
                                            {i.name}
                                        </td>


                                    </tr>
                                ))

                            }

                            </tbody>
                        </table>

                    </div>

                </div>
            }


        </div>
    );
}

export default Component;
