import {KeyValuePair, OptionType} from "src/types/common";
import Button from "./Button";
import React, {useState} from "react";
import Modal from "../Modal";
import FormField from "./FormField";
import TextEditor from "./TextEditor";
import {ChoiceEditor} from "./ChoiceEditor";
import {MdModeEditOutline, MdOutlineRemoveCircle} from "react-icons/md";
import {HiPlusCircle} from "react-icons/hi"

type Props = Omit<React.JSX.IntrinsicElements['input'], "onChange"> & {
    onAdd?: (value: KeyValuePair) => void
    onRemove?: (value: KeyValuePair) => void
    values?: KeyValuePair[]
    title?: string,
    keyLabel?: string,
    valueLabel?: string
    valueAutoGeneratedOnAdd?: boolean
    addLabel?: string
    keyOptions?: OptionType[]
    onEdit?: (value: KeyValuePair) => void
    hideEmptyLabel?: boolean
    valueRenderer?: (value: string, onChange: (v: string) => void) => React.ReactNode
    validate?: (value: KeyValuePair) => string | null
    valuePlaceholder?: string
}

const Component: React.FC<Props> = ({

                                        values,
                                        onAdd,
                                        onRemove,
                                        title,
                                        keyLabel,
                                        valueLabel,
                                        addLabel,
                                        valueAutoGeneratedOnAdd,
                                        keyOptions,
                                        hideEmptyLabel,
                                        onEdit,
                                        valueRenderer,
                                        validate,
                                        valuePlaceholder
                                    }) => {

    const [mode, setMode] = useState<"NONE" | "EDIT" | "ADD">("NONE");
    const [modalError, setModalError] = useState<string | null>(null);


    const [newKeyValue, setNewKeyValue] = useState<KeyValuePair>({
        key: '',
        value: ''
    });

    const onCloseModal = () => {
        setMode("NONE")
        setModalError(null)
        setNewKeyValue({
            key: '',
            value: ''
        })
    }

    const onAddSubmit = () => {
        if (newKeyValue) {
            if (validate) {
                const error = validate(newKeyValue);
                if (error) {
                    setModalError(error);
                    return;
                }
            }
            setModalError(null);
            onAdd!(newKeyValue)
            setNewKeyValue({key: '', value: ''})
            onCloseModal()
        }
    }
    const onEditSubmit = () => {
        if (newKeyValue) {
            if (validate) {
                const error = validate(newKeyValue);
                if (error) {
                    setModalError(error);
                    return;
                }
            }
            setModalError(null);
            onEdit?.(newKeyValue)
            setNewKeyValue({key: '', value: ''})
            onCloseModal()
        }
    }

    const onPressEdit = (value: KeyValuePair) => {
        setNewKeyValue(value)
        setMode("EDIT")
    }

    return (
        <div className={"w-100 w-full bg-white "}>
            {(['EDIT', 'ADD'].includes(mode)) &&
                <Modal onClose={onCloseModal} submitLabel={"Save"}
                       onSubmit={() => mode === "EDIT" ? onEditSubmit() : onAddSubmit()}>
                    <div className="flex flex-col gap-5">
                        {/* Header */}
                        <div className="border-b border-gray-100 pb-3">
                            <h2 className="text-base font-semibold text-gray-800">{addLabel}</h2>
                        </div>

                        {/* Inline error */}
                        {modalError && (
                            <div className="flex items-start gap-2 bg-red-50 border border-red-200 rounded-md px-3 py-2">
                                <span className="text-xs text-red-600">{modalError}</span>
                            </div>
                        )}

                        {/* Key field */}
                        <FormField title={keyLabel ?? ""} className="grow">
                            {(!keyOptions || mode === "EDIT") &&
                                <TextEditor
                                    disabled={mode === "EDIT"}
                                    placeholder={`e.g. Customer Name`}
                                    value={newKeyValue.key}
                                    onChange={(t) => setNewKeyValue({...newKeyValue, key: t})}/>
                            }
                            {(keyOptions && mode !== "EDIT") &&
                                <ChoiceEditor
                                    options={keyOptions}
                                    optionValue={(item) => item.id}
                                    optionTitle={(item) => item.title}
                                    value={newKeyValue.key}
                                    autoFocus={true}
                                    disabled={keyOptions?.length === 0}
                                    onChange={(t) => setNewKeyValue({...newKeyValue, key: t})}/>
                            }
                        </FormField>

                        {/* Value field */}
                        {!valueAutoGeneratedOnAdd && (
                            <FormField title={valueLabel ?? ""} className="grow">
                                {valueRenderer
                                    ? valueRenderer(newKeyValue.value, (v) => setNewKeyValue({...newKeyValue, value: v}))
                                    : <textarea
                                        rows={3}
                                        placeholder={valuePlaceholder ?? `Enter ${valueLabel ?? 'value'}…`}
                                        className="w-full border border-gray-300 rounded-md shadow-sm p-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary-400 resize-y"
                                        onChange={(t) => setNewKeyValue({...newKeyValue, value: t.target.value})}
                                        value={newKeyValue?.value}/>
                                }
                            </FormField>
                        )}
                    </div>
                </Modal>}
            <table className="appearance-none w-full max-w-100">
                <thead className="border-y bg-gray-50">
                <tr>
                    <th scope="col"
                        className="text-md font-semibold  text-slate-800 md:px-6 py-2 text-left">
                        {title}
                    </th>
                    <th scope="col"
                        className="text-sm font-medium text-gray-900 md:px-6 py-2 text-left">

                    </th>
                    <th scope="col"
                        className="text-sm font-medium text-gray-900 md:px-6 py-2 text-right">
                        {
                            keyOptions?.length != 0 &&
                            <div onClick={() => setMode("ADD")}
                                 className={"text-green-600 rounded w-5 h-5"}><HiPlusCircle
                                size={25}/></div>
                        }

                    </th>
                </tr>
                <tr>
                    <th scope="col"
                        className="text-sm font-medium text-gray-900 md:px-6 py-2 text-left">
                        {keyLabel}
                    </th>
                    <th scope="col"
                        className="text-sm font-medium text-gray-900 md:px-6 py-2 text-left">
                        {valueLabel}
                    </th>
                    <th scope="col"
                        className="text-sm font-medium text-gray-900 md:px-6 py-2 text-left">

                    </th>
                </tr>
                </thead>
                <tbody>
                {
                    values && values.length > 0 ?
                        values?.map((i) => (
                            <tr key={`${i.key}_${i.value}`} className="bg-white border-b">
                                <td
                                    className="text-sm text-gray-900 font-light md:px-6 py-4 whitespace-nowrap">
                                    {i.key}
                                </td>
                                <td
                                    className="text-sm w-100 text-gray-900 font-light md:px-4 py-4 break-all">
                                    {i.value}
                                </td>
                                <td
                                    className="text-sm text-gray-900 flex items-center font-light md:px-6 py-4 ">
                                    {
                                        onEdit && <Button variant={"none"} onClick={() => {
                                            onPressEdit(i)
                                        }}>
                                            <MdModeEditOutline className={"text-yellow-300"} size={21}/>
                                        </Button>
                                    }

                                    <Button
                                        variant={"none"}
                                        onClick={() => onRemove!(i)}
                                    >
                                        <MdOutlineRemoveCircle className={"text-primary-600"} size={21}/>
                                    </Button>
                                </td>


                            </tr>
                        )) : <tr>{((!hideEmptyLabel) &&
                            <td colSpan={3} className={"md:px-4 py-3"}>No {title}</td>)}
                        </tr>
                }
                </tbody>
            </table>
        </div>
    );
};

export default Component;
