name: Bitween UI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy-main:
    if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'workflow_dispatch' }}
    uses: simplify9/.github/.github/workflows/sw-cicd.yml@main
    with:
      major-version: '8'
      minor-version: '1'
      dockerfile-path: './Dockerfile'
      docker-context: '.'
      docker-platforms: 'linux/amd64'
      chart-name: 'bitweenui'
      chart-path: './chart'
      deploy-to-development: true
      development-namespace: 'playground'
      container-registry: 'ghcr.io'
      image-name: 'simplify9/bitweenui'
      helm-set-values: 'ingress.enabled=true,ingress.host=app-dev.bitween.io,ingress.tlsSecret=bitween-tls,ingress.annotations.cert-manager\.io/cluster-issuer=letsencrypt-nginx'
    secrets:
    # Container registry (using GitHub packages)
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
      kubeconfig: ${{ secrets.S9DEV_KUBECONFIG }}
      github-token: ${{ secrets.GITHUB_TOKEN }}